[package]
name = "blair"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[workspace]
members = [
  "crates/protocol",
  "crates/blur-protocol",
  "crates/integration",
  "integrations/blair-integration-dbus",
  "crates/client",
]
default-members = ["."]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 1

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Blair contributors"]
description = "A small Wayland compositor built with Smithay"
keywords = ["wayland", "compositor", "smithay"]
categories = ["gui"]
homepage = "https://github.com/sammwyy/blair"
repository = "https://github.com/sammwyy/blair"

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
notify = "6"
regex = "1"
zbus = { version = "5", default-features = false, features = ["tokio"] }
signal-hook = "0.3"
smithay = { version = "0.7.0", features = [
  "wayland_frontend",
  "backend_winit",
  "backend_drm",
  "backend_gbm",
  "backend_egl",
  "backend_udev",
  "backend_session_libseat",
  "backend_libinput",
  "use_system_lib",
  "renderer_gl",
  "renderer_pixman",
  "desktop",
] }
wayland-server = "0.31"
xcursor = "0.3"
profiling = "1"

blair-protocol = { version = "0.1.0", path = "crates/protocol" }
blair-blur-protocol = { version = "0.1.0", path = "crates/blur-protocol" }
blair-integration = { version = "0.1.0", path = "crates/integration" }
blair-integration-dbus = { version = "0.1.0", path = "integrations/blair-integration-dbus" }
blair-client = { version = "0.1.0", path = "crates/client" }

[features]
profile-with-tracy = ["profiling/profile-with-tracy", "dep:tracy-client"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
notify.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dirs.workspace = true
signal-hook.workspace = true
blair-protocol.workspace = true
blair-integration.workspace = true
blair-integration-dbus.workspace = true
smithay.workspace = true
wayland-server.workspace = true
blair-blur-protocol = { workspace = true, features = ["server"] }
xcursor.workspace = true
profiling.workspace = true
png = "0.17"
fontdue = "0.9"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
creamui-theme = { version = "0.1.2", path = "../creamui/crates/theme" }
creamui-theme-loader = { version = "0.1.1", path = "../creamui/crates/theme-loader" }
creamui-fonts = { version = "0.1.1", path = "../creamui/crates/fonts" }
tracy-client = { version = "0.18", optional = true }
