[package]
name = "blair-client"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description = "Async D-Bus client for the Blair Wayland compositor"
homepage.workspace = true
repository.workspace = true

[dependencies]
blair-protocol.workspace = true
blair-integration-dbus.workspace = true
zbus.workspace = true
tokio.workspace = true
tracing.workspace = true
futures-util = { version = "0.3", default-features = false, features = ["std"] }
