[package]
name = "blair-blur-protocol"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description = "Wayland wire protocol for blair's background-blur extension"
homepage.workspace = true
repository.workspace = true

[features]
client = ["dep:wayland-client", "wayland-protocols/client"]
server = ["dep:wayland-server", "wayland-protocols/server"]

[dependencies]
wayland-backend = "0.3"
wayland-protocols = "0.32"
wayland-scanner = "0.31"
wayland-client = { version = "0.31", optional = true }
wayland-server = { version = "0.31", optional = true }
