[package]
name = "blair"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
profile-with-tracy = ["profiling/profile-with-tracy", "dep:tracy-client"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
notify.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dirs.workspace = true
signal-hook.workspace = true
blair-protocol.workspace = true
blair-integration.workspace = true
blair-integration-dbus.workspace = true
smithay.workspace = true
wayland-server.workspace = true
xcursor.workspace = true
profiling.workspace = true
png = "0.17"
fontdue = "0.9"
creamui-theme = { path = "../../../creamui/crates/theme" }
creamui-theme-loader = { path = "../../../creamui/crates/theme-loader" }
creamui-fonts = { path = "../../../creamui/crates/fonts" }
tracy-client = { version = "0.18", optional = true }
